dataset: PASCAL
num_classes: 2
resolution: 224
backbone: unet # No effect yet

pretrained_model: None

train_kwargs:
  batch_size: 64

val_kwargs:
  batch_size: 128

# Optimizer
epochs: 40
optimizer: sgd
optimizer_kwargs:
   lr: 0.01
   weight_decay: 0.0001
   momentum: 0.9
   nesterov: False
scheduler: poly

seggcn_kwargs:
  K: 128
  T: 0.1

gcn_kwargs:
  ndim: 64
  hidden_channels: 32
  output_dim: 32

logs:
  writing_freq: 5