dataset: PASCAL
num_classes: 21
resolution: 224
backbone: resnet38_aff
backbone_kwargs:  # It only has effect on resnet
  dilated: False
head:
  type: linear
  model: deeplab

pretrained_backbone: None

train_kwargs:
  batch_size: 8
  lambda_contrastive: 0.5

val_kwargs:
  batch_size: 16

# Optimizer
epochs: 120
optimizer: sgd
optimizer_kwargs:
   lr: 0.01
   weight_decay: 0.0001
   momentum: 0.9
   nesterov: False
scheduler: poly


logs:
  writing_freq: 10