dataset: PASCAL
num_classes: 21
resolution: 224
backbone: resnet18
backbone_kwargs:  # It only has effect on resnet
  dilated: True
head:
  type: linear
  model: deeplab


pretrained_model: None

train_kwargs:
  batch_size: 32
  lambda_contrastive: 0.5

val_kwargs:
  batch_size: 128

# Optimizer
epochs: 120
optimizer: sgd
optimizer_kwargs:
   lr: 0.01
   weight_decay: 0.0001
   momentum: 0.9
   nesterov: False
scheduler: poly

seggcn_kwargs:
  K: 128
  T: 0.5

gcn_kwargs:
  ndim: 64
  hidden_channels: 32
  output_dim: 32

logs:
  writing_freq: 10